#include <fstream>
#include <sstream>

int main(){
    std::ifstream in("bf_out.txt");
    std::ofstream out("itemsets.py");
    out << "\"\"\"This file was generated by Converter.cpp, it uses the NDI implementation to generate a "
           "python module containing a list of itemsets.\"\"\"\n";
    out << "Itemsets = [\n";
    std::string line;
    while (std::getline(in, line)) {
        out << "    frozenset(";
        std::istringstream iss(line);
        std::string item;
        while (std::getline(iss, item, ' ')) {
            if (item.front() == '(' || item.front() == '['){
                break;
            }
            out << item << ", ";
        }

        out << "),\n";
    }
    out << "]\n";
    return 0;
}
